name: Karabiner-DriverKit-SMAppServiceExample

targets:
  Karabiner-DriverKit-SMAppServiceExample:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-SMAppServiceExample
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
      - path: Resources
        excludes:
          - Info.plist.in
    dependencies:
      - sdk: ServiceManagement.framework
