name: Karabiner-DriverKit-SMAppServiceExample

targets:
  Karabiner-DriverKit-SMAppServiceExample:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-SMAppServiceExample
      # SMAppService.register requires valid codesigning
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
      - path: Resources
        excludes:
          - Info.plist.in
    dependencies:
      - sdk: ServiceManagement.framework
