name: cli

targets:
  cli:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - include
      SYSTEM_HEADER_SEARCH_PATHS:
        - vendor/include
    type: tool
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
    dependencies:
      - sdk: CoreServices.framework
