name: Karabiner-DriverKit-CLI

targets:
  cli:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-CLI
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      HEADER_SEARCH_PATHS:
        - include
      SYSTEM_HEADER_SEARCH_PATHS:
        - vendor/include
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: Resources
        excludes:
          - Info.plist.in
    dependencies:
      - sdk: CoreServices.framework
