name: Karabiner-DriverKit-VirtualHIDDeviceClient

targets:
  Karabiner-DriverKit-VirtualHIDDeviceClient:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-VirtualHIDDeviceClient
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SWIFT_OBJC_BRIDGING_HEADER: 'Karabiner-DriverKit-VirtualHIDDeviceClient/Bridging-Header.h'
      SYSTEM_HEADER_SEARCH_PATHS:
        - vendor/include
        - ../../include
        - ../../../include
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: Karabiner-DriverKit-VirtualHIDDeviceClient
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=gnu++17'
        excludes:
          - Info.plist.in
