name: Karabiner-DriverKit-ExtensionManager

packages:
  SwiftShell:
    url: https://github.com/kareman/SwiftShell
    from: 5.0.1

targets:
  Karabiner-DriverKit-ExtensionManager:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-ExtensionManager
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: ExtensionManager
        compilerFlags:
          - -Werror
        excludes:
          - entitlements.plist
          - Info.plist.in
    dependencies:
      - package: SwiftShell

# DriverKit directory is not managed by project.yml since XcodeGen does not support DriverKit project yet
