name: KarabinerDriverKitVirtualHIDDevice

targets:
  KarabinerDriverKitVirtualHIDDevice:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.KarabinerDriverKitVirtualHIDDevice
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: ExtensionManager
        compilerFlags:
          - -Werror
        excludes:
          - entitlements.plist
          - Info.plist.in

# DriverKit directory is not managed by project.yml since XcodeGen does not support DriverKit project yet
