name: Karabiner-DriverKit-VirtualHIDDevice

packages:
  SwiftShell:
    url: https://github.com/kareman/SwiftShell
    # from: 5.0.1
    # We use master because v5.0.1 does not support Xcode 12.
    branch: master

targets:
  Karabiner-VirtualHIDDevice-Manager:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-VirtualHIDDevice-Manager
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: ExtensionManager
        compilerFlags:
          - -Wall
          - -Werror
        excludes:
          - .gitignore
          - embedded.provisionprofile
          - entitlements.plist
          - Info.plist.in
    dependencies:
      - package: SwiftShell
# DriverKit directory is not managed by project.yml since XcodeGen does not support DriverKit project yet
