name: Karabiner-DriverKit-VirtualHIDDeviceClient

targets:
  Karabiner-DriverKit-VirtualHIDDeviceClient:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-DriverKit-VirtualHIDDeviceClient
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - vendor/include
        - ../../include
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=gnu++17'
      - path: include
      - path: vendor/include
      - path: ../../include
    dependencies:
      - sdk: CoreFoundation.framework
      - sdk: IOKit.framework
