name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: examples
        run: make -C examples
      - name: tests
        run: make -C tests
