name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: brew install
        run: brew install xcodegen
      - name: examples
        run: make -C examples
      - name: tests
        run: make -C tests
