name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: brew install
        run: brew install xcodegen
      - name: examples
        run: make -C examples
      - name: tests
        run: make -C tests
